// <auto-generated />
using System;
using DiplomServer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405135132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DiplomServer.Domain.Entities.GroupDiscipline", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("AttestTypeId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("DisciplineId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("GroupId")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("StudyYear")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "DisciplineId", "AttestTypeId", "Semester", "StudyYear")
                        .IsUnique();

                    b.ToTable("GroupDisciplines", (string)null);
                });

            modelBuilder.Entity("DiplomServer.Domain.Entities.RetakeDirection", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("CreatedById")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("GroupDisciplineId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Number")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RetakeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("GroupDisciplineId");

                    b.ToTable("RetakeDirections", (string)null);
                });

            modelBuilder.Entity("DiplomServer.Domain.Entities.RetakeDirectionStudent", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("RetakeDirectionId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("RetakeGradeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RetakeGradeValue")
                        .HasColumnType("int");

                    b.Property<bool>("RetakeIsPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("StudentId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("RetakeDirectionId", "StudentId")
                        .IsUnique();

                    b.ToTable("RetakeDirectionStudents", (string)null);
                });

            modelBuilder.Entity("DiplomServer.Domain.Entities.RetakeDirection", b =>
                {
                    b.HasOne("DiplomServer.Domain.Entities.GroupDiscipline", "GroupDiscipline")
                        .WithMany("RetakeDirections")
                        .HasForeignKey("GroupDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupDiscipline");
                });

            modelBuilder.Entity("DiplomServer.Domain.Entities.RetakeDirectionStudent", b =>
                {
                    b.HasOne("DiplomServer.Domain.Entities.RetakeDirection", "RetakeDirection")
                        .WithMany("RetakeDirectionStudents")
                        .HasForeignKey("RetakeDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetakeDirection");
                });

            modelBuilder.Entity("DiplomServer.Domain.Entities.GroupDiscipline", b =>
                {
                    b.Navigation("RetakeDirections");
                });

            modelBuilder.Entity("DiplomServer.Domain.Entities.RetakeDirection", b =>
                {
                    b.Navigation("RetakeDirectionStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
